version: "3.8"

services:
  paymybuddy-backend:
    image: localhost:5000/paymybuddy-backend:latest
    container_name: springpage
    ports:
      - "8090:8080"
    env_file:
      - .env
    depends_on:
      paymybuddy-db:
        condition: service_healthy
    networks:
      - spring-network

  paymybuddy-db:
    image: mysql:8
    container_name: mysql
    env_file:
      - .env
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - spring-network

    # ðŸ”¥ OBLIGATOIRE pour que backend attende que MySQL soit prÃªt
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s

networks:
  spring-network:

