version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    container_name: springpage
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_paymybuddy
    
    depends_on:
      - db
    
    networks:
      - spring-network
    
      
  db:
   image: mysql:8
   container_name: mysql
   environment:
     MYSQL_ROOT_PASSWORD: rootpass
     MYSQL_DATABASE: db_paymybuddy  

   volumes: 
     - ./initdb:/docker-entrypoint-init.d
   networks:
     - spring-network
   ports:
     - "3306:3306"
    
networks:
  spring-network:
