version: "3.8"

services:
  paymybuddy-backend:
    image: paymybuddy 
    container_name: springpage
    ports:
      - "8080:8080"
    env_file:
      - .env
    
    depends_on:
      - paymybuddy-db
    networks:
      - spring-network

  paymybuddy-db:
    image: mysql:8
    container_name: mysql
    env_file:
      - .env
      
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - spring-network
    ports:
      - "3306:3306"

networks:
  spring-network:

